DROP TABLE user_roles
IF EXISTS;
DROP TABLE meals
IF EXISTS;
DROP TABLE restaurant
IF EXISTS;
DROP TABLE users
IF EXISTS;
DROP SEQUENCE global_seq
IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ
  AS INTEGER
    START WITH 100000;

CREATE TABLE users
(
  id         INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name       VARCHAR(255) NOT NULL,
  email      VARCHAR(255) NOT NULL,
  password   VARCHAR(255) NOT NULL,
  registered TIMESTAMP DEFAULT now(),
  enabled    BOOLEAN   DEFAULT TRUE,
  voted_id   INTEGER      NOT NULL,
  voted_date TIMESTAMP DEFAULT NULL,
  FOREIGN KEY ( voted_id ) REFERENCES restaurant (id)
);
CREATE UNIQUE INDEX users_unique_email_idx
  ON users (email);

CREATE TABLE user_roles
(
  user_id INTEGER NOT NULL,
  role    VARCHAR(255),
  CONSTRAINT user_roles_idx UNIQUE (user_id, role),
  FOREIGN KEY ( user_id ) REFERENCES users (id)
    ON DELETE CASCADE
);


CREATE TABLE restaurant
(
  id    INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name  VARCHAR(255) NOT NULL,
  votes INT          NOT NULL
);
CREATE UNIQUE INDEX restaurant_unique_name_idx
  ON restaurant (name);


CREATE TABLE meals
(
  id            INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  description   VARCHAR(255) NOT NULL,
  price         INT          NOT NULL,
  restaurant_id INTEGER      NOT NULL,
  in_menu       BOOLEAN DEFAULT FALSE,
  FOREIGN KEY ( restaurant_id ) REFERENCES restaurant (id)
    ON DELETE CASCADE
);
CREATE INDEX meals_in_menu_idx
  ON meals (in_menu, restaurant_id);